# Configuration GitFlow recommandée
restrictions:
  main:
    required_status_checks:
      - "Tests Qualité & Sécurité"
      - "Build & Tests Docker"
      - "Tests d'Intégration"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2

  develop:
    required_status_checks:
      - "Tests Qualité & Sécurité"
      - "Build & Tests Docker"
    required_pull_request_reviews:
      required_approving_review_count: 1
